### ISSUE TITLE
QOL optimizations and bug fixes

### ISSUE THREAD

**Issue by leohigabr** [GabrielRioo/TaskBuilder#3]
QOL:
When clicking "Adicionar" button, remove the alert message.
Save tasks even when user refreshes the page or closes the browser.
Add an option to import or export tasks.

Bug fixes:
When adding a new task, you can insert blank strings.
Close button color stays red when hovering after finishing a task.
If task content is longer than 58 characters, the text overrides the close button.
If task content is longer than 55 characters, the text overrides the close button when hovering.

**Comment by GabrielRioo** [comment]
Alert Message removed!
Im already working to save tasks when refresh and I will try to put this option to import  or export!!

Thank you for your help! I'll work fix this bugs too.
